# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43\x61lculator.proto\x12\ncalculator\"H\n\x07Request\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12!\n\x02op\x18\x03 \x01(\x0e\x32\x15.calculator.Operation\"\x17\n\x05Reply\x12\x0e\n\x06result\x18\x01 \x01(\x05*6\n\tOperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x07\n\x03SUB\x10\x01\x12\x0b\n\x07PRODUCT\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\x32\x83\x01\n\tCalculate\x12\x35\n\tCalculate\x12\x13.calculator.Request\x1a\x11.calculator.Reply\"\x00\x12?\n\x0fStreamCalculate\x12\x13.calculator.Request\x1a\x11.calculator.Reply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_OPERATION']._serialized_start=131
  _globals['_OPERATION']._serialized_end=185
  _globals['_REQUEST']._serialized_start=32
  _globals['_REQUEST']._serialized_end=104
  _globals['_REPLY']._serialized_start=106
  _globals['_REPLY']._serialized_end=129
  _globals['_CALCULATE']._serialized_start=188
  _globals['_CALCULATE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
